In [50]:
from collections import Counter, defaultdict
import pandas as pd
import glob
import os
import re

from Bio import SeqIO

# Get frequency of amino acids for all virus

In [51]:
df_taxid_ref_seq = pd.read_csv('./data/refseq/acc2taxid.csv', index_col=0)
df_taxid_ref_seq.head()

                   taxid
refseq_id
GCF_000861825.2    10407
GCF_000852945.1    10990
GCF_000861085.1    11082
GCF_004789575.1  1133363
GCF_002829625.1  1157337

In [52]:
path = '../viral_spectra/virus_raw_nuc_aa'
all_path = []
for root,dirs,files in os.walk(path):
    if root[len(path):].count(os.sep) < depth:
        for f in files:
            all_path.append(os.path.join(root, f))

In [53]:
all_path_nucl = [k for k in all_path if 'cds_from_genomic.fna' in k]
all_path_protein = [k for k in all_path if 'protein.faa' in k]

## For aminoacids

In [54]:
all_path_protein = glob.glob('./data/refseq/ncbi_dataset/ncbi_dataset/data/*/protein.faa')

In [55]:
all_ref_seqs = [x.split('/')[-2] for x in all_path_protein]
all_ref_seqs[:2]

['GCF_000848685.1', 'GCF_000851385.1']

In [56]:
list_of_seq_protein = []

for path in all_path_protein:
    ref_seq = path.split('/')[-2]
    fasta = SeqIO.parse(path, 'fasta')
    for record in fasta:
        dictionary = {'refseq_id': ref_seq}
        dictionary.update(Counter(record.seq))
        list_of_seq_protein.append(dictionary)
len(list_of_seq_protein)

207

In [66]:
df = pd.DataFrame(list_of_seq_protein)
df_aa = df.groupby(['refseq_id']).sum().drop(columns=['X'])
df_aa.head()

,M,A,S,N,H,V,T,L,F,D,E,I,G,C,Y,Q,R,P,K,W
refseq_id,,,,,,,,,,,,,,,,,,,,
GCF_000848685.1,170,617.0,681,516.0,175.0,892.0,565,830,514.0,504.0,357.0,444,628.0,301.0,418.0,266.0,329.0,327.0,490.0,107.0
GCF_000851385.1,135,232.0,420,228.0,127.0,330.0,298,474,213.0,296.0,340.0,350,215.0,93.0,199.0,149.0,215.0,184.0,394.0,57.0
GCF_000852585.1,80,189.0,206,134.0,69.0,206.0,161,244,115.0,156.0,172.0,175,159.0,57.0,115.0,116.0,162.0,152.0,159.0,57.0
GCF_000852945.1,227,370.0,860,669.0,230.0,586.0,536,956,598.0,587.0,536.0,671,355.0,149.0,402.0,305.0,394.0,326.0,626.0,70.0
GCF_000853785.1,115,181.0,312,230.0,102.0,182.0,227,359,207.0,225.0,256.0,353,177.0,110.0,156.0,133.0,178.0,124.0,318.0,47.0

In [67]:
df_aa.sum(axis=1).sort_values(ascending=False)

refseq_id
GCF_009858895.2    9744.0
GCF_000852945.1    9453.0
GCF_000848685.1    9131.0
GCF_002985995.1    9007.0
GCF_000862965.1    8801.0
GCF_003092915.1    7616.0
GCF_006298385.1    7601.0
GCF_002829625.1    7600.0
GCF_000862745.1    6671.0
GCF_000885335.1    6204.0
GCF_000862265.1    6204.0
GCF_000858185.1    5924.0
GCF_000851385.1    4949.0
GCF_000865725.1    4789.0
GCF_000861085.1    4621.0
GCF_000860505.1    4452.0
GCF_000856445.1    4446.0
GCF_002815375.1    4163.0
GCF_000853785.1    3992.0
GCF_004789575.1    3981.0
GCF_000871205.1    3976.0
GCF_000870765.1    3602.0
GCF_000871845.1    3391.0
GCF_000861845.1    3172.0
GCF_000852585.1    2884.0
GCF_000862005.1    2873.0
GCF_000864005.1    2531.0
GCF_002826225.1    2476.0
GCF_002816555.1    2332.0
GCF_000861825.2    2277.0
GCF_000861165.1    2209.0
GCF_000861905.1    2193.0
GCF_002816725.1    2188.0
GCF_000854405.1    1671.0
dtype: float64

In [68]:
df_aa.astype(int)

,M,A,S,N,H,V,T,L,F,D,E,I,G,C,Y,Q,R,P,K,W
refseq_id,,,,,,,,,,,,,,,,,,,,
GCF_000848685.1,170,617,681,516,175,892,565,830,514,504,357,444,628,301,418,266,329,327,490,107
GCF_000851385.1,135,232,420,228,127,330,298,474,213,296,340,350,215,93,199,149,215,184,394,57
GCF_000852585.1,80,189,206,134,69,206,161,244,115,156,172,175,159,57,115,116,162,152,159,57
GCF_000852945.1,227,370,860,669,230,586,536,956,598,587,536,671,355,149,402,305,394,326,626,70
GCF_000853785.1,115,181,312,230,102,182,227,359,207,225,256,353,177,110,156,133,178,124,318,47
GCF_000854405.1,52,91,119,56,33,105,136,156,67,86,84,100,111,70,46,81,67,77,107,27
GCF_000856445.1,107,183,350,353,109,231,353,485,163,215,227,397,171,80,181,125,153,164,362,37
GCF_000858185.1,159,374,436,401,136,469,344,546,223,391,316,401,319,75,253,179,278,196,392,36
GCF_000860505.1,143,242,342,203,104,324,264,392,240,262,240,284,276,86,156,182,176,192,272,72
GCF_000861085.1,148,378,280,174,95,362,345,404,147,206,277,233,408,94,115,114,268,190,261,122
GCF_000861165.1,67,161,151,117,51,138,170,179,84,117,111,133,142,42,98,81,96,119,124,28
GCF_000861825.2,44,121,232,75,62,118,150,291,128,62,59,93,146,83,62,83,144,202,51,71
GCF_000861845.1,60,295,232,89,69,254,226,319,89,122,119,133,273,107,99,90,199,225,96,76
GCF_000861905.1,51,168,154,108,52,150,154,179,89,116,108,135,153,42,87,87,99,122,108,31
GCF_000862005.1,60,278,201,51,50,278,188,303,87,127,129,102,258,94,81,61,174,193,83,75
GCF_000862265.1,122,381,626,245,122,583,340,615,332,379,306,271,356,143,233,114,453,233,308,42
GCF_000862745.1,128,581,499,197,161,556,387,696,286,297,312,260,467,200,171,224,374,471,280,124
GCF_000862965.1,156,585,592,496,154,806,519,764,484,484,403,465,546,289,419,328,310,337,547,117
GCF_000864005.1,69,196,188,106,57,174,159,207,92,135,138,125,212,33,63,117,133,165,122,40
GCF_000865725.1,189,274,363,255,85,264,300,390,186,210,359,311,313,87,133,186,322,187,296,79
GCF_000870765.1,92,174,349,150,78,207,190,384,160,216,197,236,205,63,130,112,212,177,211,59
GCF_000871205.1,116,203,291,240,100,206,244,366,188,224,210,349,161,110,170,150,161,137,307,43
GCF_000871845.1,132,224,192,137,67,217,261,314,100,133,241,220,274,57,72,102,195,146,217,90
GCF_000885335.1,223,397,326,246,133,409,306,517,237,375,494,462,358,73,239,254,447,245,388,75
GCF_002815375.1,102,239,364,232,77,254,290,416,139,195,271,313,197,76,135,146,187,154,331,45
GCF_002816555.1,56,199,121,108,62,186,164,195,111,140,133,102,158,35,82,78,108,130,140,24
GCF_002816725.1,58,152,146,113,56,143,159,171,96,117,103,154,149,44,87,80,94,120,118,28
GCF_002826225.1,35,275,174,72,67,182,173,236,98,109,108,100,182,55,72,83,178,196,47,34
GCF_002829625.1,223,553,612,338,141,584,562,717,298,474,330,448,469,102,240,265,403,406,320,115
GCF_002985995.1,199,578,622,557,150,804,566,750,496,488,421,529,574,290,429,272,308,304,557,113
GCF_003092915.1,228,643,660,343,150,552,539,737,289,463,286,387,386,103,253,308,416,476,276,121
GCF_004789575.1,126,197,308,224,100,193,244,353,182,218,221,361,167,121,178,147,163,138,296,44
GCF_006298385.1,249,601,636,314,147,552,473,724,269,482,317,436,432,100,267,344,431,430,277,120
GCF_009858895.2,207,658,661,532,189,781,718,930,500,511,442,513,576,296,448,365,350,394,562,111

In [72]:
aa_content = df_taxid_ref_seq.join(df_aa.astype(int))
aa_content.to_csv('data/aminoacid_freq_all_virus.csv')
aa_content.head()

,taxid,M,A,S,N,H,V,T,L,F,...,E,I,G,C,Y,Q,R,P,K,W
refseq_id,,,,,,,,,,,,,,,,,,,,,
GCF_000861825.2,10407,44,121,232,75,62,118,150,291,128,...,59,93,146,83,62,83,144,202,51,71
GCF_000852945.1,10990,227,370,860,669,230,586,536,956,598,...,536,671,355,149,402,305,394,326,626,70
GCF_000861085.1,11082,148,378,280,174,95,362,345,404,147,...,277,233,408,94,115,114,268,190,261,122
GCF_004789575.1,1133363,126,197,308,224,100,193,244,353,182,...,221,361,167,121,178,147,163,138,296,44
GCF_002829625.1,1157337,223,553,612,338,141,584,562,717,298,...,330,448,469,102,240,265,403,406,320,115

## For nucleotids

In [11]:
all_ref_seqs = [x.split('\\')[3] for x in all_path_nucl]

In [12]:
list_of_seq_nucl = []

for path, ref_seq in zip(all_path_nucl, all_ref_seqs):
    
    fasta = list(SeqIO.parse(path, 'fasta'))
    
    for record in fasta:
        dictionary = {'refseq_id':ref_seq}
        dictionary.update(Counter(record.seq))
        list_of_seq_nucl.append(dictionary)
        # list_of_seq.append(dict({'taxid':11082}))
        # list_of_seq.append(Counter(record.seq))

In [13]:
df = pd.DataFrame(list_of_seq_nucl)
df_nucl = df.groupby(['refseq_id']).sum()
df_nucl = df_nucl.drop(columns=['Y','R','W','K'])
df_nucl

                     A      T     G     C
refseq_id
GCF_000848685.1   6794   9126  6252  5239
GCF_000851385.1   4846   4089  3255  2678
GCF_000852585.1   2535   2695  1994  1400
GCF_000852945.1   9275   9480  4895  4751
GCF_000853785.1   4317   3394  2287  1990
GCF_000854405.1   1574   1419  1114   915
GCF_000858185.1   5707   5204  3923  2974
GCF_000860505.1   4039   4375  2887  2061
GCF_000861085.1   3778   3028  3904  3159
GCF_000861165.1   2016   1563  1514  1537
GCF_000861825.2   1479   1981  1493  1899
GCF_000861845.1   1882   2011  2739  2890
GCF_000861905.1   1829   1619  1560  1574
GCF_000862005.1   1546   2004  2750  2322
GCF_000862265.1   4505   5666  4723  3751
GCF_000862745.1   5811   6937  7352  7455
GCF_000862965.1  11022  12757  8393  6114
GCF_000864005.1   2094   1844  1874  1790
GCF_000870765.1   3069   2848  2596  2308
GCF_000871205.1   4124   3378  2279  2159
GCF_000871845.1   3375   2148  2574  2079
GCF_000885335.1   6133   4673  4765  3071
GCF_002815375.1   4692   3202  2447  2175
GCF_002816555.1   1776   1484  1793  1946
GCF_002816725.1   2154   1749  1370  1294
GCF_002826225.1   1249   1829  1945  2414
GCF_002829625.1   5852   6195  5291  5495
GCF_002985995.1  11438  12968  8118  6568
GCF_003092915.1   5537   6316  5391  5641
GCF_004789575.1   4203   3455  2244  2053
GCF_006298385.1   5994   6188  5678  4973
GCF_009858895.2  12688  13709  8393  7693

In [14]:
df_nucl = df_nucl.div(df_nucl.sum(axis=1), axis=0)
df_nucl

                        A         T         G         C
refseq_id
GCF_000848685.1  0.247857  0.332932  0.228084  0.191128
GCF_000851385.1  0.325935  0.275020  0.218927  0.180118
GCF_000852585.1  0.293947  0.312500  0.231215  0.162338
GCF_000852945.1  0.326573  0.333791  0.172353  0.167283
GCF_000853785.1  0.360110  0.283116  0.190774  0.165999
GCF_000854405.1  0.313421  0.282557  0.221824  0.182198
GCF_000858185.1  0.320474  0.292228  0.220294  0.167004
GCF_000860505.1  0.302275  0.327421  0.216060  0.154243
GCF_000861085.1  0.272406  0.218329  0.281491  0.227774
GCF_000861165.1  0.304072  0.235747  0.228356  0.231825
GCF_000861825.2  0.215849  0.289113  0.217893  0.277145
GCF_000861845.1  0.197648  0.211195  0.287650  0.303508
GCF_000861905.1  0.277879  0.245974  0.237010  0.239137
GCF_000862005.1  0.179309  0.232429  0.318952  0.269311
GCF_000862265.1  0.241620  0.303888  0.253312  0.201180
GCF_000862745.1  0.210887  0.251751  0.266812  0.270550
GCF_000862965.1  0.287886  0.333203  0.219219  0.159693
GCF_000864005.1  0.275454  0.242568  0.246514  0.235464
GCF_000870765.1  0.283615  0.263192  0.239904  0.213289
GCF_000871205.1  0.345394  0.282915  0.190871  0.180821
GCF_000871845.1  0.331663  0.211085  0.252948  0.204304
GCF_000885335.1  0.328988  0.250671  0.255606  0.164736
GCF_002815375.1  0.374880  0.255833  0.195510  0.173778
GCF_002816555.1  0.253751  0.212030  0.256179  0.278040
GCF_002816725.1  0.328004  0.266332  0.208619  0.197046
GCF_002826225.1  0.167944  0.245932  0.261530  0.324593
GCF_002829625.1  0.256296  0.271318  0.231726  0.240660
GCF_002985995.1  0.292592  0.331730  0.207664  0.168014
GCF_003092915.1  0.241949  0.275989  0.235569  0.246493
GCF_004789575.1  0.351568  0.289000  0.187704  0.171727
GCF_006298385.1  0.262515  0.271011  0.248675  0.217799
GCF_009858895.2  0.298661  0.322694  0.197561  0.181084

In [15]:
df_nucl = df_taxid_ref_seq.join(df_nucl)
df_nucl

                   taxid         A         T         G         C
refseq_id
GCF_000861825.2    10407  0.215849  0.289113  0.217893  0.277145
GCF_000852945.1    10990  0.326573  0.333791  0.172353  0.167283
GCF_000861085.1    11082  0.272406  0.218329  0.281491  0.227774
GCF_004789575.1  1133363  0.351568  0.289000  0.187704  0.171727
GCF_002829625.1  1157337  0.256296  0.271318  0.231726  0.240660
GCF_000853785.1   118655  0.360110  0.283116  0.190774  0.165999
GCF_000864005.1    11983  0.275454  0.242568  0.246514  0.235464
GCF_000860505.1    12092  0.302275  0.327421  0.216060  0.154243
GCF_002816555.1    12110  0.253751  0.212030  0.256179  0.278040
GCF_000862265.1    12162  0.241620  0.303888  0.253312  0.201180
GCF_000871845.1    12637  0.331663  0.211085  0.252948  0.204304
GCF_000861905.1   138948  0.277879  0.245974  0.237010  0.239137
GCF_000861165.1   138950  0.304072  0.235747  0.228356  0.231825
GCF_002816725.1   138951  0.328004  0.266332  0.208619  0.197046
GCF_002815375.1   162145  0.374880  0.255833  0.195510  0.173778
GCF_002826225.1  1678143  0.167944  0.245932  0.261530  0.324593
GCF_000871205.1  1933178  0.345394  0.282915  0.190871  0.180821
GCF_000852585.1   198112  0.293947  0.312500  0.231215  0.162338
GCF_009858895.2  2697049  0.298661  0.322694  0.197561  0.181084
GCF_000848685.1    28295  0.247857  0.332932  0.228084  0.191128
GCF_000862745.1    28344  0.210887  0.251751  0.266812  0.270550
GCF_000861845.1  3052230  0.197648  0.211195  0.287650  0.303508
GCF_000854405.1  3052493  0.313421  0.282557  0.221824  0.182198
GCF_000851385.1  3052763  0.325935  0.275020  0.218927  0.180118
GCF_006298385.1   351073  0.262515  0.271011  0.248675  0.217799
GCF_003092915.1    38170  0.241949  0.275989  0.235569  0.246493
GCF_000885335.1    40054  0.328988  0.250671  0.255606  0.164736
GCF_000862005.1    54290  0.179309  0.232429  0.318952  0.269311
GCF_000870765.1    57482  0.283615  0.263192  0.239904  0.213289
GCF_002985995.1   693997  0.292592  0.331730  0.207664  0.168014
GCF_000862965.1   694014  0.287886  0.333203  0.219219  0.159693
GCF_000858185.1    77763  0.320474  0.292228  0.220294  0.167004

In [16]:
# df_nucl.to_csv('../viral_spectra/data/nucl_all_freq_all_virus.csv')

## For 4f codons

In [25]:
# dict for four-fold codons
FOUR_FOLD_CODONS = {
    'GGT', 'GGC', 'GGA', 'GGG',  # Glycine (G)
    'CCT', 'CCC', 'CCA', 'CCG',  # Proline (P)
    'GCT', 'GCC', 'GCA', 'GCG',  # Alanine (A)
    'GTT', 'GTC', 'GTA', 'GTG',  # Valine (V)
    'ACT', 'ACC', 'ACA', 'ACG',   # Threonine (T)
    'CTT', 'CTC', 'CTA', 'CTG'    # Leucine (L) - only C-starting
}

def parse_location(location_str):
    #Parses str location and return a list of range
    if 'join(' in location_str:
        ranges = re.findall(r'(\d+)\.\.(\d+)', location_str)
        return [(int(start), int(end)) for start, end in ranges]
    else:
        start, end = re.findall(r'(\d+)\.\.(\d+)', location_str)[0]
        return [(int(start), int(end))]

def is_within_join(join_ranges, test_range):
    #Checks if test_range is inside any of join_ranges
    test_start, test_end = test_range[0]
    for (join_start, join_end) in join_ranges:
        if join_start <= test_start and test_end <= join_end:
            return True
    return False

def process_fasta_files(path_to_files):
    # Collect all records and location
    all_records = []
    join_records = []
    
    for file_path in path_to_files:
        refseq_id = os.path.basename(os.path.dirname(file_path))
        with open(file_path, 'r') as f:
            for record in SeqIO.parse(f, 'fasta'):
                # Extract location from description
                location_match = re.search(r'\[location=([^\]]+)\]', record.description)
                if location_match:
                    location_str = location_match.group(1)
                    location_ranges = parse_location(location_str)
                    all_records.append({
                        'refseq_id': refseq_id,
                        'record': record,
                        'location': location_ranges,
                        'is_join': 'join(' in location_str
                    })
                    if 'join(' in location_str:
                        join_records.append((refseq_id, location_ranges))
    
    # Filtered records: delete locations are included in the join records
    filtered_records = []
    for record_info in all_records:
        keep = True
        if not record_info['is_join']:
            for (refseq_id, join_ranges) in join_records:
                if record_info['refseq_id'] == refseq_id and is_within_join(join_ranges, record_info['location']):
                    keep = False
                    break
        if keep:
            filtered_records.append(record_info)
    
    return filtered_records

def count_four_fold_sites(sequence):
    #Count four-fold degenerate sites в последовательности"""
    counts = {'A': 0, 'T': 0, 'G': 0, 'C': 0}
    sequence = sequence.upper()
    
    for i in range(0, len(sequence) - 2, 3):
        codon = sequence[i:i+3]
        if len(codon) != 3:
            continue
        
        # Check 4f codon
        if codon in FOUR_FOLD_CODONS:
            third_nt = codon[2]
            if third_nt in counts:
                counts[third_nt] += 1
    
    return counts

def analyze_filtered_records(filtered_records):
    results = defaultdict(lambda: {'A': 0, 'T': 0, 'G': 0, 'C': 0})
    
    for record_info in filtered_records:
        refseq_id = record_info['refseq_id']
        sequence = str(record_info['record'].seq)
        counts = count_four_fold_sites(sequence)
        
        for nt, count in counts.items():
            results[refseq_id][nt] += count
    
    
    df = pd.DataFrame.from_dict(results, orient='index')
    df.index.name = 'refseq_id'
    return df.sort_index()

In [26]:
filtered_records = process_fasta_files(all_path_nucl)
df_4f = analyze_filtered_records(filtered_records)
df_4f

                    A     T    G     C
refseq_id
GCF_000848685.1   684  1793  395   656
GCF_000851385.1   485   541  270   267
GCF_000852585.1   253   415  164    82
GCF_000852945.1   646  1234  273   393
GCF_000853785.1   454   325  130   157
GCF_000854405.1   237   212   81    73
GCF_000858185.1   587   816  305   214
GCF_000860505.1   442   670  170   148
GCF_000861085.1   553   447  473   520
GCF_000861165.1   273   217  169   189
GCF_000861825.2   209   266  159   216
GCF_000861845.1   215   299  444   584
GCF_000861905.1   230   240  152   247
GCF_000862005.1   184   305  482   427
GCF_000862265.1   288   905  586   374
GCF_000862745.1   651  1157  951  1342
GCF_000862965.1  1360  2351  503   492
GCF_000864005.1   275   313  174   288
GCF_000870765.1   310   306  283   280
GCF_000871205.1   431   350  175   191
GCF_000871845.1   550   226  267   287
GCF_000885335.1   678   412  580   237
GCF_002815375.1   586   377  171   207
GCF_002816555.1   181   242  238   329
GCF_002816725.1   315   262  103   136
GCF_002826225.1   117   356  228   502
GCF_002829625.1   632  1181  589   669
GCF_002985995.1  1270  2320  503   593
GCF_003092915.1   575  1093  753   640
GCF_004789575.1   461   342  145   160
GCF_006298385.1   742   917  780   451
GCF_009858895.2  1484  2763  364   712

In [27]:
df_4f = df_4f.div(df_4f.sum(axis=1), axis=0)
df_4f

                        A         T         G         C
refseq_id
GCF_000848685.1  0.193878  0.508220  0.111961  0.185941
GCF_000851385.1  0.310301  0.346129  0.172745  0.170825
GCF_000852585.1  0.276805  0.454048  0.179431  0.089716
GCF_000852945.1  0.253731  0.484682  0.107227  0.154360
GCF_000853785.1  0.425891  0.304878  0.121951  0.147280
GCF_000854405.1  0.393035  0.351575  0.134328  0.121061
GCF_000858185.1  0.305411  0.424558  0.158689  0.111342
GCF_000860505.1  0.309091  0.468531  0.118881  0.103497
GCF_000861085.1  0.277471  0.224285  0.237331  0.260913
GCF_000861165.1  0.321934  0.255896  0.199292  0.222877
GCF_000861825.2  0.245882  0.312941  0.187059  0.254118
GCF_000861845.1  0.139429  0.193904  0.287938  0.378729
GCF_000861905.1  0.264672  0.276180  0.174914  0.284235
GCF_000862005.1  0.131617  0.218169  0.344778  0.305436
GCF_000862265.1  0.133767  0.420344  0.272178  0.173711
GCF_000862745.1  0.158742  0.282126  0.231895  0.327237
GCF_000862965.1  0.288993  0.499575  0.106885  0.104547
GCF_000864005.1  0.261905  0.298095  0.165714  0.274286
GCF_000870765.1  0.262935  0.259542  0.240034  0.237489
GCF_000871205.1  0.375763  0.305144  0.152572  0.166521
GCF_000871845.1  0.413534  0.169925  0.200752  0.215789
GCF_000885335.1  0.355532  0.216046  0.304143  0.124279
GCF_002815375.1  0.436987  0.281133  0.127517  0.154362
GCF_002816555.1  0.182828  0.244444  0.240404  0.332323
GCF_002816725.1  0.386029  0.321078  0.126225  0.166667
GCF_002826225.1  0.097257  0.295927  0.189526  0.417290
GCF_002829625.1  0.205796  0.384565  0.191794  0.217844
GCF_002985995.1  0.271020  0.495092  0.107341  0.126547
GCF_003092915.1  0.187847  0.357073  0.245998  0.209082
GCF_004789575.1  0.416065  0.308664  0.130866  0.144404
GCF_006298385.1  0.256747  0.317301  0.269896  0.156055
GCF_009858895.2  0.278790  0.519068  0.068382  0.133759

In [28]:
df_4f = df_taxid_ref_seq.join(df_4f)
df_4f

                   taxid         A         T         G         C
refseq_id
GCF_000861825.2    10407  0.245882  0.312941  0.187059  0.254118
GCF_000852945.1    10990  0.253731  0.484682  0.107227  0.154360
GCF_000861085.1    11082  0.277471  0.224285  0.237331  0.260913
GCF_004789575.1  1133363  0.416065  0.308664  0.130866  0.144404
GCF_002829625.1  1157337  0.205796  0.384565  0.191794  0.217844
GCF_000853785.1   118655  0.425891  0.304878  0.121951  0.147280
GCF_000864005.1    11983  0.261905  0.298095  0.165714  0.274286
GCF_000860505.1    12092  0.309091  0.468531  0.118881  0.103497
GCF_002816555.1    12110  0.182828  0.244444  0.240404  0.332323
GCF_000862265.1    12162  0.133767  0.420344  0.272178  0.173711
GCF_000871845.1    12637  0.413534  0.169925  0.200752  0.215789
GCF_000861905.1   138948  0.264672  0.276180  0.174914  0.284235
GCF_000861165.1   138950  0.321934  0.255896  0.199292  0.222877
GCF_002816725.1   138951  0.386029  0.321078  0.126225  0.166667
GCF_002815375.1   162145  0.436987  0.281133  0.127517  0.154362
GCF_002826225.1  1678143  0.097257  0.295927  0.189526  0.417290
GCF_000871205.1  1933178  0.375763  0.305144  0.152572  0.166521
GCF_000852585.1   198112  0.276805  0.454048  0.179431  0.089716
GCF_009858895.2  2697049  0.278790  0.519068  0.068382  0.133759
GCF_000848685.1    28295  0.193878  0.508220  0.111961  0.185941
GCF_000862745.1    28344  0.158742  0.282126  0.231895  0.327237
GCF_000861845.1  3052230  0.139429  0.193904  0.287938  0.378729
GCF_000854405.1  3052493  0.393035  0.351575  0.134328  0.121061
GCF_000851385.1  3052763  0.310301  0.346129  0.172745  0.170825
GCF_006298385.1   351073  0.256747  0.317301  0.269896  0.156055
GCF_003092915.1    38170  0.187847  0.357073  0.245998  0.209082
GCF_000885335.1    40054  0.355532  0.216046  0.304143  0.124279
GCF_000862005.1    54290  0.131617  0.218169  0.344778  0.305436
GCF_000870765.1    57482  0.262935  0.259542  0.240034  0.237489
GCF_002985995.1   693997  0.271020  0.495092  0.107341  0.126547
GCF_000862965.1   694014  0.288993  0.499575  0.106885  0.104547
GCF_000858185.1    77763  0.305411  0.424558  0.158689  0.111342

In [30]:
# df_4f.to_csv('../viral_spectra/data/nucl_4f_freq_all_virus.csv')